apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: flink-sql-session
spec:
  mode: native
  image: localhost:5001/flink-avro:1.20.3
  imagePullPolicy: Always
  flinkVersion: v1_20
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "2"
  serviceAccount: flink
  jobManager:
    resource:
      memory: "2048m"
      cpu: 0.5
  taskManager:
    resource:
      memory: "2048m"
      cpu: 0.5